apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-deployment1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pipeline-deployment1
  template:
    metadata:
      labels:
        app: pipeline-deployment1
    spec:
      containers:
      - name: pipeline-deployment1
        image: royjith/cube:version-2
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: pipeline-deployment1
